### ISSUE TITLE
Server not pulling mods

### ISSUE THREAD

**Issue by NeoDragonXDA** [WhyKickAmooCow/dsp-docker-server#1]
Since the last patch from nebula, the container is not pulling the mods anymore.
It seems to be broken aswell, putting the mods manually in the plugin folder, weird planetary bug on start ( titanium on starter planet, no trees etc )

Here's the last output of a fresh install

`Success! App '1366540' fully installed.
## GAME INSTALL COMPLETE
Will download the following plugins: nebula/NebulaMultiplayerMod,nebula/NebulaMultiplayerModApi,PhantomGamers/IlLine,CommonAPI/CommonAPI,starfi5h/BulletTime,xiaoye97/LDBTool,CommonAPI/DSPModSave,
## Attempting to download BepInEx from https://github.com/BepInEx/BepInEx/releases/download/v5.4.22/BepInEx_x64_5.4.22.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  607k  100  607k    0     0   915k      0 --:--:-- --:--:-- --:--:--  915k
## Attempting to download  v from Thunderstore.io
`

**Comment by WhyKickAmooCow** [comment]
The container should now work. It has undergone major changes, and I haven't kept up with changes in the nebula mod so let me know if there are any problems. See the readme for known ones.

I'm not sure about the issue with no trees, I can't seem to replicate it.
